#!/usr/bin/env python3
"""
One-time script to backfill MarketPrice entries for all stations.

Run inside the gameserver container:
    docker compose exec gameserver python backfill_market_prices.py

History:
- Originally fixed a legacy bug where the Python ``GalaxyGenerator`` created
  stations with commodities JSONB but no ``MarketPrice`` rows. The trading
  endpoint reads from the ``market_prices`` table, so stations without these
  rows showed empty resources and trading was non-functional.
- Phase 4 of the sw2102-bang cutover removed ``GalaxyGenerator``. The
  ``bang_import_service`` translator emits ``MarketPrice`` rows alongside
  station rows in the same transaction, so post-cutover galaxies should
  never be missing prices. This script is retained as an idempotent repair
  tool for legacy databases generated by the old Python pipeline, and to
  cover the unlikely case where a future translator change drops the
  invariant. The spread logic originally lifted verbatim from
  ``GalaxyGenerator.backfill_market_prices`` (galaxy_service.py:909-976)
  now lives in ``src.core.market_bootstrap.build_market_prices``, shared
  with the bang translator so both paths price stations identically.
"""

import sys
import os
import logging

# Ensure the src module is importable
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from src.core.database import SessionLocal
from src.core.market_bootstrap import build_market_prices
from src.models.station import Station
from src.models.market_transaction import MarketPrice

logger = logging.getLogger(__name__)


def backfill_market_prices(db) -> dict:
    """Create MarketPrice rows for any Station that has commodities JSONB but
    no matching market_prices entries. Idempotent: stations that already have
    prices are skipped. Returns a dict with counts.
    """
    stats = {"stations_processed": 0, "prices_created": 0, "stations_skipped": 0}

    all_stations = db.query(Station).all()

    for station in all_stations:
        existing_count = (
            db.query(MarketPrice).filter(MarketPrice.station_id == station.id).count()
        )

        if existing_count > 0:
            stats["stations_skipped"] += 1
            continue

        if not station.commodities:
            stats["stations_skipped"] += 1
            continue

        stats["stations_processed"] += 1

        for market_price in build_market_prices(station.id, station.commodities):
            db.add(market_price)
            stats["prices_created"] += 1

    db.commit()
    logger.info("MarketPrice backfill complete: %s", stats)
    return stats


def main() -> None:
    print("Starting MarketPrice backfill...")
    db = SessionLocal()
    try:
        stats = backfill_market_prices(db)
        print("\nBackfill complete!")
        print(f"  Stations processed: {stats['stations_processed']}")
        print(f"  Market prices created: {stats['prices_created']}")
        print(f"  Stations skipped (already had prices): {stats['stations_skipped']}")
    except Exception as e:
        print(f"ERROR: {e}")
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    main()
