"""intrasystem_layout parity proof + sector_destination_pools leg-generation
coverage (WO-TRANCHE-0716 ISP-PARITY).

The `EXPECTED_*` vectors below were generated by running the REAL, unmodified
player-client module (services/player-client/src/components/tactical/
windshieldTableauLayout.ts) via `npx vite-node` against the SAME inputs
exercised here — zero client files touched, zero mocking of the client math.
`EXPECTED_LIVE_*` go one step further: they were computed from THREE live
sectors' actual orbit_au/phase_deg values (sectors 1, 10, 11 — pulled
read-only from the gameserver container's own `generate_system(...,
read_only=True)`, the exact function GET /sectors/{id}/contents calls to
build the client's SystemSnapshot), fed through that same real client module.
See this WO's own report for the full parity table / tolerance statement.
"""
from __future__ import annotations

import math
import uuid

from src.services.celestial_service import _MASK64 as _CELESTIAL_MASK64
from src.services.celestial_service import SECTOR_SEED_SALT, _make_stations
from src.services.intrasystem_layout import (
    LAYOUT_BAND_HEIGHT_PX,
    LAYOUT_BAND_REM_PX,
    LAYOUT_BAND_WIDTH_PX,
    ORBIT_AU_MAX,
    ORBIT_AU_MIN,
    PLANET_FOOTPRINT_EM_MAX,
    STATION_FOOTPRINT_EM_HEIGHT_MAX,
    STATION_FOOTPRINT_EM_WIDTH_MAX,
    SectorLayout,
    fnv1a32,
    orbital_position,
    safe_orbit_radii,
    star_anchor,
)
from src.services.intrasystem_movement_service import (
    MOVE_MS,
    ORIENT_MS,
    empty_idle_pose,
    sector_destination_pools,
    start_burn,
)

# ---------------------------------------------------------------------------
# Client-parity vectors (starAnchor(sectorId, null, []))
# ---------------------------------------------------------------------------

EXPECTED_STAR = {
    1: (11.172604221850634, 42.13984580151737),
    2: (13.772586915642023, 44.70813475549221),
    5: (12.14569978392683, 42.244604140520096),
    21: (13.499544233549386, 48.37721120379865),
    999: (9.3023161937017, 48.10806970484555),
}

# ---------------------------------------------------------------------------
# Client-parity vectors (orbitalPosition(star, orbit_au, phase_deg, safeRadii)
# at FLIGHT_BAND = {widthPx:1440, heightPx:334.7, remPx:18.09} — the real
# resolved `.ssv-tableau` geometry WindshieldTableau.test.tsx's own FLIGHT_BAND
# constant asserts against).
# ---------------------------------------------------------------------------

EXPECTED_POSITION = [
    # (sector_id, orbit_au, phase_deg, kind, expected_x_pct, expected_y_pct)
    (1, 0.2, 0, "planet", 24.25174483857304, 42.13984580151737),
    (1, 0.95, 90, "planet", 98.366875, 92.97370779802809),
    (1, 0.5, 180, "planet", 46.05031253311037, 42.13984580151737),
    (1, 0.5, 270, "planet", 52.58988284147157, 23.659028117546075),
    (2, 0.35, 45, "planet", 41.5223057453978, 57.28194517515654),
    (2, 0.6, 200, "station", 53.393730899244304, 37.969394453119925),
    (21, 0.22, 10, "planet", 28.396073260190768, 50.170581814390054),
    (21, 0.82, 350, "station", 85.62803475568293, 43.15142633543697),
    (5, 0.9, 120, "planet", 95.85209072286452, 83.86504964657738),
    (5, 0.25, 300, "station", 25.63548065597327, 35.69642567639873),
]

# Live-sector ground truth: sectors 1/10/11's REAL orbit_au/phase_deg (from
# generate_system(..., read_only=True) on the live gameserver container,
# 2026-07-16), run through the real client module.
EXPECTED_LIVE = {
    1: {
        "bodies": [
            (0.2507, 118, 20.536364942200187, 53.9844011348283),
            (0.4176, 119, 39.83969236087476, 61.68365657280469),
            (0.5784, 251, 59.57551477724482, 21.92597302358456),
            (0.6802, 228, 69.16393298800814, 23.456215547793633),
            (0.8275, 160, 84.51952845271914, 57.2841452159761),
            (0.9438, 135, 98.366875, 77.8502261174711),
        ],
        "stations": [
            (0.7305, 51, 74.43680340487549, 68.6415483539923),
        ],
    },
    10: {
        "bodies": [
            (0.3784, 329, 43.131796199336705, 40.439710804366854),
            (0.7164, 181, 70.74646666280972, 48.51031415211161),
            (0.9784, 295, 98.366875, 10.964857285335931),
        ],
        "stations": [
            (0.658, 127, 59.48788157802338, 69.76521630509343),
        ],
    },
    # Body #2 here has orbit_au=1.0 -- LIVE data exceeding windshieldTableauLayout
    # .ts's own ORBIT_AU_MAX=0.95 doc-comment claim (that citation covers
    # celestial_service.py's STATION orbit ceiling; procedural BODY orbits come
    # from a separate cumulative-walk normalized to <=1.0 display radius,
    # generate_orbits's own docstring) -- both the client and this port clamp
    # abs(orbit_au) to ORBIT_AU_MAX before use, so the two stay identical
    # regardless; exercised here deliberately, not filtered out.
    11: {
        "bodies": [
            (0.3864, 301, 42.26062510172941, 30.199109777835517),
            (0.685, 13, 80.31196742864657, 50.772727483790185),
            (1.0, 332, 98.366875, 25.900443827456495),
        ],
        "stations": [
            (0.2266, 147, 14.068033614080871, 48.30362203358633),
        ],
    },
}

TOL_PCT = 1e-6  # essentially exact -- both sides run the identical algorithm


def _radii(star, max_w, max_h=None):
    return safe_orbit_radii(star, LAYOUT_BAND_WIDTH_PX, LAYOUT_BAND_HEIGHT_PX, LAYOUT_BAND_REM_PX, max_w, max_h)


def test_star_anchor_matches_client_exactly():
    for sector_id, (ex, ey) in EXPECTED_STAR.items():
        s = star_anchor(sector_id)
        assert abs(s.x_pct - ex) < TOL_PCT, f"sector {sector_id} x"
        assert abs(s.y_pct - ey) < TOL_PCT, f"sector {sector_id} y"


def test_star_anchor_uses_one_continuing_stream_not_two_independent_ones():
    """Regression guard: a prior server implementation derived x/y from two
    INDEPENDENT `:x`/`:y`-suffixed hashes -- a different number sequence than
    the client's single stream, two sequential draws. Pin the real client
    numbers so that bug can't silently return."""
    s = star_anchor(1)
    assert abs(s.x_pct - 11.172604221850634) < TOL_PCT
    assert abs(s.y_pct - 42.13984580151737) < TOL_PCT


def test_orbital_position_matches_client_exactly():
    for sector_id, orbit_au, phase_deg, kind, ex, ey in EXPECTED_POSITION:
        star = star_anchor(sector_id)
        max_w = PLANET_FOOTPRINT_EM_MAX if kind == "planet" else STATION_FOOTPRINT_EM_WIDTH_MAX
        max_h = None if kind == "planet" else STATION_FOOTPRINT_EM_HEIGHT_MAX
        radii = _radii(star, max_w, max_h)
        x, y = orbital_position(star, orbit_au, phase_deg, radii)
        assert abs(x - ex) < TOL_PCT, f"sector {sector_id} au={orbit_au} phase={phase_deg} x"
        assert abs(y - ey) < TOL_PCT, f"sector {sector_id} au={orbit_au} phase={phase_deg} y"


def test_sector_layout_matches_client_on_three_live_sectors():
    """Cross-language parity proof against REAL sector data (sectors 1, 10,
    11) -- not hand-picked synthetic orbit_au/phase_deg. See module docstring
    for provenance."""
    max_err = 0.0
    for sector_id, data in EXPECTED_LIVE.items():
        layout = SectorLayout(sector_id)
        for orbit_au, phase_deg, ex, ey in data["bodies"]:
            x, y = layout.planet_position(orbit_au, phase_deg)
            max_err = max(max_err, abs(x - ex), abs(y - ey))
        for orbit_au, phase_deg, ex, ey in data["stations"]:
            x, y = layout.station_position(orbit_au, phase_deg)
            max_err = max(max_err, abs(x - ex), abs(y - ey))
    assert max_err < TOL_PCT, f"max per-axis delta {max_err} exceeds tolerance {TOL_PCT}"


def test_fnv1a32_matches_client_hash_for_ascii_seed_strings():
    # rng.ts's fnv1a32('windshield-tableau:star:1') -- verified via node.
    assert fnv1a32("windshield-tableau:star:1") == 1725791716


def test_safe_orbit_radii_final_box_is_always_in_bounds():
    for sector_id in range(1, 30):
        star = star_anchor(sector_id)
        for max_w, max_h in (
            (PLANET_FOOTPRINT_EM_MAX, None),
            (STATION_FOOTPRINT_EM_WIDTH_MAX, STATION_FOOTPRINT_EM_HEIGHT_MAX),
        ):
            radii = _radii(star, max_w, max_h)
            assert 0 <= radii.x_min_pct <= radii.x_max_pct <= 100
            assert 0 <= radii.y_min_pct <= radii.y_max_pct <= 100


def test_orbital_position_never_leaves_0_100_band_for_any_phase():
    star = star_anchor(7)
    planet_radii = _radii(star, PLANET_FOOTPRINT_EM_MAX)
    station_radii = _radii(star, STATION_FOOTPRINT_EM_WIDTH_MAX, STATION_FOOTPRINT_EM_HEIGHT_MAX)
    for radii in (planet_radii, station_radii):
        for phase_deg in range(0, 360, 5):
            for orbit_au in (ORBIT_AU_MIN, 0.4, 0.7, ORBIT_AU_MAX, 1.0, -0.3):
                x, y = orbital_position(star, orbit_au, phase_deg, radii)
                assert 0.0 <= x <= 100.0
                assert 0.0 <= y <= 100.0


def test_orbital_position_x_is_monotonic_in_orbit_au_at_fixed_phase():
    """T0-1's own contract: further out = further right, phase-independent
    primary term -- two different orbit_au values must never collapse onto
    the same X (the exact bug T0-1 fixed client-side)."""
    star = star_anchor(3)
    radii = _radii(star, PLANET_FOOTPRINT_EM_MAX)
    xs = [orbital_position(star, au, 200, radii)[0] for au in (0.2, 0.35, 0.5, 0.65, 0.8, 0.95)]
    assert xs == sorted(xs)
    assert xs[0] < xs[-1] - 1.0  # a real spread, not a flat line


# ---------------------------------------------------------------------------
# sector_destination_pools -- leg-generation coverage (DB-free FakeSession)
# ---------------------------------------------------------------------------


class _Row:
    def __init__(self, **kw):
        self.__dict__.update(kw)


class _FakeQuery:
    def __init__(self, rows):
        self._rows = list(rows)

    def filter(self, *args, **kwargs):
        return self

    def first(self):
        return self._rows[0] if self._rows else None

    def all(self):
        return list(self._rows)

    def limit(self, n):
        return self

    def with_for_update(self):
        return self


class _FakeSession:
    """Routes db.query(Model) by class name -- no real filter interpretation
    (each test pre-scopes its rows to the one sector under test)."""

    def __init__(self, *, sector=None, planets=None, stations=None, celestial_row=None):
        self._sector = sector
        self._planets = planets or []
        self._stations = stations or []
        self._celestial_row = celestial_row

    def query(self, model):
        name = getattr(model, "__name__", "")
        if name == "Sector":
            return _FakeQuery([self._sector] if self._sector is not None else [])
        if name == "Planet":
            return _FakeQuery(self._planets)
        if name == "Station":
            return _FakeQuery(self._stations)
        if name == "SectorCelestial":
            return _FakeQuery([self._celestial_row] if self._celestial_row is not None else [])
        return _FakeQuery([])


def _fake_sector(sector_id: int):
    return _Row(id=f"uuid-{sector_id}", sector_id=sector_id)


def _fake_planet(planet_id, *, habitability_score=0, kind="BARREN", position=3):
    """Every attribute celestial_service._merge_real_planets actually reads
    off a real Planet row (id/type/habitability_score/display_name/
    discovered_by/owner_id) -- a fake missing one of these raises
    AttributeError the instant a test exercises the real-planet merge path,
    not a silently-wrong value."""
    return _Row(
        id=planet_id,
        habitability_score=habitability_score,
        position=position,
        type=_Row(value=kind, name=kind),
        display_name=f"Planet-{str(planet_id)[:8]}",
        discovered_by=None,
        owner_id=None,
    )


def _fake_station(station_id, *, name="Dock"):
    return _Row(id=station_id, name=name, type=_Row(value="TRADING_POST"), sector_id=None)


def test_sector_destination_pools_positions_bodies_via_layout():
    """A sector whose persisted skeleton has real bodies/stations already
    merged (the common steady-state case) -- pools land exactly where
    SectorLayout places them, and every position is a real %-space point."""
    sector_id = 42
    composition = {
        "bodies": [
            {"orbit_au": 0.3, "phase_deg": 60, "kind": "TERRAN", "real": False, "planet_id": None},
            {"orbit_au": 0.7, "phase_deg": 210, "kind": "BARREN", "real": False, "planet_id": None},
        ],
        "stations": [],
    }
    celestial_row = _Row(composition=composition)
    session = _FakeSession(sector=_fake_sector(sector_id), planets=[], stations=[], celestial_row=celestial_row)

    pools = sector_destination_pools(session, sector_id, "npc-ship-1")

    layout = SectorLayout(sector_id)
    ex0 = layout.planet_position(0.3, 60)
    ex1 = layout.planet_position(0.7, 210)

    all_planets = pools["habitable"] + pools["barren"]
    assert len(all_planets) == 2
    got = {(round(p["x_pct"], 6), round(p["y_pct"], 6)) for p in all_planets}
    expected = {(round(ex0[0], 6), round(ex0[1], 6)), (round(ex1[0], 6), round(ex1[1], 6))}
    assert got == expected
    # TERRAN body buckets habitable, BARREN buckets barren.
    assert len(pools["habitable"]) == 1
    assert len(pools["barren"]) == 1
    assert len(pools["outbound"]) == 3  # always-populated seeded rim scatter


def test_sector_destination_pools_positions_station_via_layout():
    """Stations are NEVER read from SectorCelestial.composition (celestial_
    service never persists them there -- see sector_destination_pools's own
    doc-comment) -- generate_system always derives them fresh from the real
    Station rows via celestial_service._make_stations. Ground-truth orbit_au/
    phase_deg here is computed by calling that SAME production function
    (not reimplemented), so this proves sector_destination_pools's station
    entries land exactly where SectorLayout places _make_stations's own
    output -- i.e. where the client actually renders that station."""
    sector_id = 43
    celestial_row = _Row(composition={"bodies": [], "stations": []})
    station = _fake_station(uuid.UUID("11111111-1111-1111-1111-111111111111"), name="Test Dock")
    session = _FakeSession(sector=_fake_sector(sector_id), planets=[], stations=[station], celestial_row=celestial_row)

    pools = sector_destination_pools(session, sector_id, "npc-ship-2")

    root_seed = (sector_id * SECTOR_SEED_SALT) & _CELESTIAL_MASK64
    expected_station = _make_stations([station], root_seed)[0]
    layout = SectorLayout(sector_id)
    ex = layout.station_position(expected_station["orbit_au"], expected_station["phase_deg"])

    assert len(pools["habitable"]) == 1
    got = pools["habitable"][0]
    assert got["target_kind"] == "station"
    assert got["target_id"] == str(station.id)
    assert abs(got["x_pct"] - ex[0]) < 1e-9
    assert abs(got["y_pct"] - ex[1]) < 1e-9


def test_sector_destination_pools_missing_sector_does_not_crash():
    session = _FakeSession(sector=None)
    pools = sector_destination_pools(session, 999999, "npc-ghost")
    assert pools["habitable"] == []
    assert pools["barren"] == []
    assert len(pools["outbound"]) == 3  # rim scatter is DB-independent


def test_sector_destination_pools_zero_body_composition_does_not_crash():
    """An existing skeleton row with an explicitly empty bodies/stations list
    (a degenerate VOID sector, e.g.) must not crash leg generation -- pools
    fall back to outbound-only, exactly like the missing-sector case."""
    sector_id = 44
    celestial_row = _Row(composition={"bodies": [], "stations": []})
    session = _FakeSession(sector=_fake_sector(sector_id), planets=[], stations=[], celestial_row=celestial_row)

    pools = sector_destination_pools(session, sector_id, "npc-void")
    assert pools["habitable"] == []
    assert pools["barren"] == []
    assert len(pools["outbound"]) == 3


def test_leg_generation_targets_a_layout_derived_position():
    """End-to-end: a destination picked from sector_destination_pools (whose
    x/y come from SectorLayout) becomes a real burn leg whose to_x/to_y match
    the layout output exactly -- the actual server-side leg-generation path
    WO-TRANCHE-0716 ISP-PARITY exists to fix."""
    sector_id = 45
    composition = {
        "bodies": [{"orbit_au": 0.4, "phase_deg": 30, "kind": "OCEANIC", "real": False, "planet_id": None}],
        "stations": [],
    }
    celestial_row = _Row(composition=composition)
    session = _FakeSession(sector=_fake_sector(sector_id), planets=[], stations=[], celestial_row=celestial_row)

    pools = sector_destination_pools(session, sector_id, "npc-trader-1")
    dest = pools["habitable"][0]

    layout = SectorLayout(sector_id)
    expected_x, expected_y = layout.planet_position(0.4, 30)
    assert abs(dest["x_pct"] - expected_x) < 1e-9
    assert abs(dest["y_pct"] - expected_y) < 1e-9

    idle = empty_idle_pose(sector_id, "npc-trader-1")
    pose = start_burn(
        idle,
        to_x=dest["x_pct"],
        to_y=dest["y_pct"],
        sector_id=sector_id,
        ship_key="npc-trader-1",
        target_kind=dest["target_kind"],
        target_id=dest["target_id"],
    )
    assert pose["leg"] is not None
    assert abs(pose["leg"]["to_x"] - expected_x) < 1e-9
    assert abs(pose["leg"]["to_y"] - expected_y) < 1e-9

    # Sampling mid-flight lands strictly between the burn's endpoints -- a
    # real leg toward the layout-computed target, not a placeholder scatter.
    from datetime import datetime, timedelta, timezone

    from src.services.intrasystem_movement_service import derive_pose

    now = datetime(2026, 7, 16, 12, 0, 0, tzinfo=timezone.utc)
    pose["leg"]["started_at"] = now.isoformat()
    mid = derive_pose(pose, now + timedelta(milliseconds=ORIENT_MS + MOVE_MS // 2))
    assert mid["phase"] in ("accelerating", "gliding", "brake_turn", "braking")


# ---------------------------------------------------------------------------
# Mack gate fixes (WO-TRANCHE-0716 ISP-PARITY, 2026-07-16)
# ---------------------------------------------------------------------------


def test_orbital_position_nan_input_yields_finite_in_band_output():
    """A malformed orbit_au/phase_deg (e.g. corrupt JSONB) must never
    propagate NaN through the safe-radii box -- Python's min/max are
    NaN-order-dependent (max(nan, x) is nan, but max(x, nan) is x), so this
    pins the explicit guard rather than trusting caller-side filtering."""
    star = star_anchor(1)
    radii = _radii(star, PLANET_FOOTPRINT_EM_MAX)

    for orbit_au, phase_deg in (
        (float("nan"), 45.0),
        (0.5, float("nan")),
        (float("nan"), float("nan")),
    ):
        x, y = orbital_position(star, orbit_au, phase_deg, radii)
        assert not math.isnan(x) and not math.isnan(y)
        assert 0.0 <= x <= 100.0
        assert 0.0 <= y <= 100.0


def test_sector_destination_pools_overflow_planets_beyond_max_bodies_still_positioned():
    """celestial_service.generate_system caps merged real planets at
    MAX_BODIES=9 -- a sector with more real planets than that used to
    silently drop the overflow from pools entirely (Mack's gate finding: 15
    in, 9 out, 6 UUIDs gone, no error). Every real planet must land
    somewhere reachable regardless of the render-side cap."""
    sector_id = 47
    celestial_row = _Row(composition={"bodies": [], "stations": []})
    planet_ids = [uuid.UUID(int=90000 + i) for i in range(15)]
    planets = [_fake_planet(pid, habitability_score=10, kind="BARREN") for pid in planet_ids]
    session = _FakeSession(sector=_fake_sector(sector_id), planets=planets, stations=[], celestial_row=celestial_row)

    pools = sector_destination_pools(session, sector_id, "npc-overflow")

    all_planets = pools["habitable"] + pools["barren"]
    got_ids = {p["target_id"] for p in all_planets}
    expected_ids = {str(pid) for pid in planet_ids}
    assert got_ids == expected_ids, f"missing: {expected_ids - got_ids}"
    assert len(all_planets) == 15  # no duplicates either

    for p in all_planets:
        assert 0.0 <= p["x_pct"] <= 100.0
        assert 0.0 <= p["y_pct"] <= 100.0


def test_sector_destination_pools_deterministic_regardless_of_row_order():
    """Determinism rests ENTIRELY on the internal str(uuid) sorts inside
    celestial_service._merge_real_planets/_make_stations -- there is no
    ORDER BY backstop anywhere in this path (Mack's gate finding). Pin it:
    identical planets/stations, different DB row order -> identical pools
    output, so removing either internal sort fails this test loudly instead
    of jittering NPC destinations silently in prod."""
    sector_id = 48
    celestial_row = _Row(composition={"bodies": [], "stations": []})
    planet_a = _fake_planet(uuid.UUID(int=9001), habitability_score=80, kind="TERRAN")
    planet_b = _fake_planet(uuid.UUID(int=9002), habitability_score=5, kind="BARREN")
    station_a = _fake_station(uuid.UUID(int=9101), name="Dock A")
    station_b = _fake_station(uuid.UUID(int=9102), name="Dock B")

    def run(planet_order, station_order):
        session = _FakeSession(
            sector=_fake_sector(sector_id),
            planets=planet_order,
            stations=station_order,
            celestial_row=celestial_row,
        )
        return sector_destination_pools(session, sector_id, "npc-shuffle")

    forward = run([planet_a, planet_b], [station_a, station_b])
    shuffled = run([planet_b, planet_a], [station_b, station_a])

    def normalize(pools):
        return {
            bucket: sorted(
                (round(e["x_pct"], 9), round(e["y_pct"], 9), e["target_kind"], e["target_id"])
                for e in entries
            )
            for bucket, entries in pools.items()
        }

    forward_n, shuffled_n = normalize(forward), normalize(shuffled)
    assert forward_n == shuffled_n
    assert any(forward_n.values())  # sanity: not accidentally empty
